name: Jekyll site CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gh-pages-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bundler Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build & Deploy to GitHub Pages
      uses: joshlarsen/jekyll4-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        # JEKYLL_DESTINATION: docs
  ssh-remote-job:
    runs-on: ubuntu-latest
    needs: [gh-pages-job]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: echo dir
      run: |
        pwd
        ls -aF        
    - name: ssh远程服务器
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "开始同步gh-pages站点站点到服务器"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.DC_HOST }}
        user: ${{ secrets.DC_USER }}
        pass: ${{ secrets.DC_PASS }}
        port: ${{ secrets.DC_PORT }}
        connect_timeout: 10s
        first_ssh: |
          rm -rf /home/site/wwwroot/jekyll-blog
          ls -la 
          hostnamectl
          echo $WELCOME 
          mkdir -p /home/site/wwwroot/jekyll-blog
        scp: |
          './*' => /home/site/wwwroot/jekyll-blog
        last_ssh: |
          echo $LASTSSH
