name: ssh发布到远程服务器

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ssh远程服务器
  uses: cross-the-world/ssh-scp-ssh-pipelines@latest
  env:
    WELCOME: "开始同步gh-pages站点站点到服务器"
    LASTSSH: "Doing something after copying"
  with:
    host: ${{ secrets.DC_HOST }}
    user: ${{ secrets.DC_USER }}
    pass: ${{ secrets.DC_PASS }}
    port: ${{ secrets.DC_PORT }}
    connect_timeout: 10s
    first_ssh: |
      rm -rf /home/site/wwwroot/jekyll-blog
      ls -la  
      echo $WELCOME 
      mkdir -p /home/site/wwwroot/jekyll-blog
    scp: |
      './*' => /home/site/wwwroot/jekyll-blog
    last_ssh: |
      echo $LASTSSH


